[project]
name = "noname"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
   "numpy>=1.26",
   "pymoo>=0.6.1.5,<0.7.0",
   "pyswarms>=1.3.0",
]
